config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :filiais
  resources :filiais
  resources :cargos
  resources :setores
  resources :funcionarios do
  	collection do
    	get :listar
  	end
  end

  get 'paginas/index'

  get 'paginas/localizacao'
  root :to => 'paginas#index'

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base

end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:codcargo, :nomecargo, :salariobase)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codcargo %><br>
    <%= f.number_field :codcargo %>
  </div>
  <div class="field">
    <%= f.label :nomecargo %><br>
    <%= f.text_field :nomecargo %>
  </div>
  <div class="field">
    <%= f.label :salariobase %><br>
    <%= f.text_field :salariobase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Codcargo</th>
      <th>Nomecargo</th>
      <th>Salariobase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.codcargo %></td>
        <td><%= cargo.nomecargo %></td>
        <td><%= cargo.salariobase %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <%= will_paginate @cargos, previous_label: "Anterior", next_label: "Próxima" %> <br/>
<%= link_to 'Novo Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codcargo:</strong>
  <%= @cargo.codcargo %>
</p>

<p>
  <strong>Nomecargo:</strong>
  <%= @cargo.nomecargo %>
</p>

<p>
  <strong>Salariobase:</strong>
  <%= @cargo.salariobase %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>