config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :filiais
  resources :filiais
  resources :cargos
  resources :setores
  resources :funcionarios do
  	collection do
    	get :listar
  	end
  end

  get 'paginas/index'

  get 'paginas/localizacao'
  root :to => 'paginas#index'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
	validates_presence_of :nome, message: "O nome deve ser preenchido"
  	validates_presence_of :endereco, message: "O Endereço deve ser preenchido"
  	validates_presence_of :telefone, message: "O telephone deve ser preenchido"

 	validates_uniqueness_of :nome, message: "Matricula já cadastrado"
  
  	validates_size_of :nome, :minimum => 3, :maximun=>50, message: "Muito pequeno ou muito grande, mínimo de 3 e máximo de 50 caracteres"
  
  	validates_numericality_of :salario, message: "O salário deve ser numérico"


	mount_uploader :foto, FotoFuncionarioUploader
	belongs_to :cargo
	belongs_to :setor


end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    # buscar o sexo
   
    @psexo = params[:psexo]
    # buscar o nome
    @pnome = params[:pnome]

    filtro = "1=1"
    
    if  @psexo ==  "M"
      filtro = filtro + " and sexo = 'M' "
    end
    if  @psexo ==  "F"
      filtro = filtro + " and sexo = 'F' "
    end

    if not(@pnome.nil?)
       filtro = filtro + " and nome like '%"+@pnome+"%'"
    end

#   @funcionarios = Funcionario.where(filtro).order("nome")
    @funcionarios = Funcionario.where(filtro).order("nome").paginate(page: params[:page], per_page: 3)

  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def listar

    @funcionarios = Funcionario.all.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.pdf do
        pdf = FuncionariosReport.new(@funcionarios)
        send_data pdf.render, filename: 'FuncionariosListagem.pdf', :width => pdf.bounds.width,
        type: 'application/pdf', disposition: :inline, :page_size => "A4", :page_layout => :portrait
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:matricula, 
        :nome, :endereco, :telefone, :salario, :sexo, :dtadmissao, :foto, :setor_id, :cargo_id)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <div class="form-inputs">
    <% if @funcionario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

        <ul>
        <% @funcionario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :matricula %><br>
      <%= f.text_field :matricula, :id => "matricula" %>
    </div>
    <div class="field">
      <%= f.label :nome %><br>
      <%= f.text_field :nome %>
    </div>
    <div class="field">
      <%= f.label :endereco %><br>
      <%= f.text_field :endereco %>
    </div>
    <div class="field">
      <%= f.label :telefone %><br>
      <%= f.text_field :telefone %>
    </div>
    <div class="field">
      <%= f.label :salario %><br>
      <%= f.text_field :salario %>
    </div>
    <div class="field">
      <%= f.label :sexo %><br>
      <%= f.radio_button :sexo, 'M', :checked => true %> Masculino
      <%= f.radio_button :sexo, 'F' %> Feminino
    </div>
    <div class="field">
      <%= f.label :dtadmissao %><br>
      <%= f.text_field :dtadmissao ,  class: "datepicker" %>
    </div>
     
    <div class="field">
      <%= f.label :setor_id %><br>
      <%= f.select :setor_id, options_for_select(Setor.all.map{|m|[m.nomesetor, m.id]},f.object.setor_id) %>
    </div>
    <div class="field">
      <%= f.label :cargo_id %><br>
      <%= f.select :cargo_id, options_for_select(Cargo.all.map{|m|[m.nomecargo, m.id]},f.object.cargo_id) %>
    </div>

    <div>
      <%= f.label :foto %>
      <%= image_tag @funcionario.foto_url, class: 'foto'  if @funcionario.foto? %>
      <%= f.file_field :foto, label: 'Foto' , input_html: {accept: ('application/jpg') } %>
      <br/>
    </div>





    <div class="actions">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', funcionarios_path ,  class: "btn btn-default " %>
    </div>
  </div>
<% end %>

<script>

$(document).ready(function(){
  $('.datepicker').datepicker({format: 'dd-mm-yyyy'});
  $('#matricula').inputmask("9999.9.999.9999");  
});
</script>

app/views/funcionarios/_formbusca.html.erb
<%= form_tag(funcionarios_path, method: "get") do %>
  <%= label_tag(:pnome, "Nome:") %>
  <%= text_field_tag(:pnome,  @pnome) %>
  <br/>
  <%= label_tag(:psexo, "Sexo:") %>
  <%= select_tag :psexo, options_for_select([['Ambos','A'],['Masculino','M'],['Feminino','F']],selected:@psexo)  %>
  <%= submit_tag 'Filtrar' %>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Alteração de Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @funcionario %> |
<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>
<hr/>
    <%= render 'formbusca' %>
<hr/>
<table >
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Salario</th>      
      <th>Sexo</th>
      <th>Cargo</th>
      <th>Setor</th>
      <th>Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.matricula %></td>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.salario %></td>        
        <td><%= funcionario.sexo %></td>
        <td><%= funcionario.cargo.nomecargo if funcionario.cargo %></td>
        <td><%= funcionario.setor.nomesetor if funcionario.setor %></td>
        <td>
          <%= link_to ' ', edit_funcionario_path(funcionario),  class: "glyphicon glyphicon-pencil" %>
          <%= link_to ' ', funcionario, method: :delete, data: { confirm: 'Are you sure?' } , class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= will_paginate @funcionarios, previous_label: "Anterior", next_label: "Próxima" %> <br/>
 <%= link_to 'Novo Funcionario', new_funcionario_path%>

app/views/funcionarios/new.html.erb
<h1>Novo Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Matricula:</strong>
  <%= @funcionario.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @funcionario.salario %>
</p>
<p>
  <strong>Sexo:</strong>
  <%= @funcionario.sexo %>
</p>
<%= link_to 'Alterar', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Voltar', funcionarios_path %>