config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :filiais
  resources :filiais
  resources :cargos
  resources :setores
  resources :funcionarios do
  	collection do
    	get :listar
  	end
  end

  get 'paginas/index'

  get 'paginas/localizacao'
  root :to => 'paginas#index'

end

app/views/layouts/_latbar.html.erb
  
<div id="wrapper">
	<div id="sidebar-wrapper">
  	<ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#" >
           <h4>Menu</h4>
        </a>
      </li>
      
      <li style="font-size: 20px;">
      	<%= link_to ' Empresa', paginas_index_path,class: "glyphicon glyphicon-home" %>  
      </li>
      <li style="font-size: 20px;">
      	<%= link_to ' Localização', paginas_localizacao_path ,class: "glyphicon glyphicon-map-marker"%>
      </li>
      <li style="font-size: 20px;">
      	<%= link_to ' Funcionários', funcionarios_path ,class: "glyphicon glyphicon-user"%>
      </li>
      <li style="font-size: 20px;">
        <%= link_to ' Setores', setores_path ,class: "glyphicon glyphicon-th-list"%>
      </li>   
      <li style="font-size: 20px;">
        <%= link_to ' Cargos', cargos_path ,class: "glyphicon  glyphicon-tag"%>
      </li>
      <li style="font-size: 20px;">
        <%= link_to ' Filiais', filiais_path ,class: "glyphicon  glyphicon-home"%>
      </li>
      <li style="font-size: 20px;">
        <%= link_to " Relatorio", listar_funcionarios_path(@funcionario,  :format => 'pdf'), target: '_blank', class: "glyphicon glyphicon-print" %> 
      </li>
  



		</ul>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-pills navbar-left">
         <li><%= image_tag "logo-iff-small.png", :height => '100%' %></li>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-left">
        <li><%= link_to ' Empresa', paginas_index_path %></li>
        <li><%= link_to ' LocalizaÁ„o', paginas_localizacao_path %></li>     
      </ul>
      <% if usuario_signed_in? %>
        <ul class="nav nav-pills navbar-right">
          <li><%= link_to 'Bem vindo:'+current_usuario.email, edit_usuario_registration_path%></li>
          <li><%= link_to "Logout", destroy_usuario_session_path, method: :delete  %></li>
        </ul>
      <% else %>
        <ul class="nav nav-pills navbar-right">
          <li><%= link_to "Cadastre-se", new_usuario_registration_path, class: 'navbar-link' %>  </li>
          <li><%= link_to "Login", new_usuario_session_path, :class => 'navbar-link'  %></li>
        </ul>
      <% end %>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Minha Empresa</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">  
        <% if usuario_signed_in? %>
          <%= render "layouts/latbar" %>
        <% end %>
      </div>
      <div class="col-md-9">
        <div class="panel-body">
          <%= yield %>  
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
    </div> <!-- row -->
  </div> <!-- container -->
</body>
</html>